alias sam="ssh -X -p 777 sam@bishoplab.psych.berkeley.edu"
alias ra="ssh -X -p 777 rashared@bishoplab.psych.berkeley.edu"
alias nx="ssh -X samyag1@ssh.neuro.berkeley.edu"
alias ipt="ipython --pylab"
alias mountStimulusSets="sshfs -p 777 -o idmap=user -o follow_symlinks rashared@bishoplab.psych.berkeley.edu:/data/stimulusSets ~/stimulusSets"
alias mountStudies="sshfs -p 777 -o idmap=user -o follow_symlinks rashared@bishoplab.psych.berkeley.edu:/data/studies ~/studies"
alias mountProjects="sshfs -p 777 -o idmap=user -o follow_symlinks rashared@bishoplab.psych.berkeley.edu:/data/projects ~/projects"
alias mountLabDocs="sshfs -p 777 -o idmap=user -o follow_symlinks rashared@bishoplab.psych.berkeley.edu:/data/labDocs ~/labDocs"
alias mountUsers="sshfs -p 777 -o idmap=user -o follow_symlinks rashared@bishoplab.psych.berkeley.edu:/data/rashared/sambadance ~/users"
alias mountNX="sshfs -o idmap=user -o follow_symlinks samyag1@ftp.neuro.berkeley.edu:/home/bishop/samyag1 ~/NX"
alias drives="mountStimulusSets; mountStudies; mountProjects; mountLabDocs; mountUsers; mountNX"
alias go="gnome-open"